In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/DV/StudentsPerformance.csv')

In [5]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

**1. STANDARDIZE / CLEAN CATEGORICAL FEATURES**

In [7]:
cat={
    'gender',
    'race/ethnicity',
    'parental level of education',
    'lunch',
    'test preparation course'
}
for i in cat:
  df[i]=df[i].str.strip().str.lower()

In [8]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group b,bachelor's degree,standard,none,72,72,74
1,female,group c,some college,standard,completed,69,90,88
2,female,group b,master's degree,standard,none,90,95,93
3,male,group a,associate's degree,free/reduced,none,47,57,44
4,male,group c,some college,standard,none,76,78,75

**2. STATISTICAL MEASURES FOR SUBJECT SCORES**

In [9]:
subjects = ['math score', 'reading score', 'writing score']
print("Mean")
print(df[subjects].mean())
print("Median")
print(df[subjects].median())
print("Standard deviation")
print(df[subjects].std())
print("quantile")
print(df[subjects].quantile([0.25, 0.50, 0.75]))

Mean
math score       66.089
reading score    69.169
writing score    68.054
dtype: float64
Median
math score       66.0
reading score    70.0
writing score    69.0
dtype: float64
Standard deviation
math score       15.163080
reading score    14.600192
writing score    15.195657
dtype: float64
quantile
      math score  reading score  writing score
0.25        57.0           59.0          57.75
0.50        66.0           70.0          69.00
0.75        77.0           79.0          79.00

**3. CREATE TOTAL MARKS AND PERCENTAGE**

In [12]:
df['total_mark']=df['math score']+df['reading score']+df['writing score']
df['percentage'] = (df['total_mark'] / 300) * 100

print("\nCalculated Features:")
df.head()

Calculated Features:

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_mark,percentage
0,female,group b,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group c,some college,standard,completed,69,90,88,247,82.333333
2,female,group b,master's degree,standard,none,90,95,93,278,92.666667
3,male,group a,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group c,some college,standard,none,76,78,75,229,76.333333

** 4. DETECT EXTREME PERFORMANCE OUTLIERS
 Using IQR method**


> Add blockquote

In [16]:
subject_columns = [
    "math score",
    "reading score",
    "writing score"
]

In [17]:

for col in subject_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower_limit) |
        (df[col] > upper_limit)
    ]

    print("\n----------------------------")
    print("Subject:", col)
    print("Q1:", Q1)
    print("Median:", df[col].median())
    print("Q3:", Q3)
    print("IQR:", IQR)
    print("Lower Limit:", lower_limit)
    print("Upper Limit:", upper_limit)
    print("Number of Outliers:", len(outliers))

    if len(outliers) > 0:
        print("Outlier Scores:")
        print(outliers[col].values)

----------------------------
Subject: math score
Q1: 57.0
Median: 66.0
Q3: 77.0
IQR: 20.0
Lower Limit: 27.0
Upper Limit: 107.0
Number of Outliers: 8
Outlier Scores:
[18  0 22 24 26 19 23  8]

----------------------------
Subject: reading score
Q1: 59.0
Median: 70.0
Q3: 79.0
IQR: 20.0
Lower Limit: 29.0
Upper Limit: 109.0
Number of Outliers: 6
Outlier Scores:
[17 26 28 23 24 24]

----------------------------
Subject: writing score
Q1: 57.75
Median: 69.0
Q3: 79.0
IQR: 21.25
Lower Limit: 25.875
Upper Limit: 110.875
Number of Outliers: 5
Outlier Scores:
[10 22 19 15 23]